/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  admin: {
    Dashboard: () => import('#controllers/admin/dashboard_controller'),
    Job: () => import('#controllers/admin/job_controller'),
    Session: () => import('#controllers/admin/session_controller'),
  },
  auth: {
    EmailVerification: () => import('#controllers/auth/email_verification_controller'),
    InvitationAcceptance: () => import('#controllers/auth/invitation_acceptance_controller'),
    PasswordReset: () => import('#controllers/auth/password_reset_controller'),
    Registration: () => import('#controllers/auth/registration_controller'),
    Session: () => import('#controllers/auth/session_controller'),
    SocialAuth: () => import('#controllers/auth/social_auth_controller'),
    TwoFactorChallenge: () => import('#controllers/auth/two_factor_challenge_controller'),
  },
  billing: {
    Billing: () => import('#controllers/billing/billing_controller'),
    Webhook: () => import('#controllers/billing/webhook_controller'),
  },
  Dashboard: () => import('#controllers/dashboard_controller'),
  files: {
    File: () => import('#controllers/files/file_controller'),
  },
  organizations: {
    Invitation: () => import('#controllers/organizations/invitation_controller'),
    Member: () => import('#controllers/organizations/member_controller'),
    Ownership: () => import('#controllers/organizations/ownership_controller'),
  },
  settings: {
    Organization: () => import('#controllers/settings/organization_controller'),
    Profile: () => import('#controllers/settings/profile_controller'),
    Security: () => import('#controllers/settings/security_controller'),
  },
  todos: {
    List: () => import('#controllers/todos/list_controller'),
    Todo: () => import('#controllers/todos/todo_controller'),
  },
}
